### PR TITLE
Fix assertion in `Run` when symlinks are present

### PR DESCRIPTION
**Pull request by SengerM**
Fix the issue encounter by a user, see [here](https://github.com/thliebig/openEMS-Project/discussions/227#discussioncomment-11202974).

### CODE REVIEW

**Comment by thliebig** [comment]
I think this was not fixed in the latest version. Currently it causes a conflict.

**Comment by thliebig** [comment]
Otherwise it looks fine

**Comment by biergaizi** [comment]
I suggest using the "fixup" or "squash" feature of git to combine three unsuccessful or partial into a single and working commit. Every git commit should be a proper and finished work, trial-and-error commits may confuse future reviewers who's digging into the code history.

**Comment by SengerM** [comment]
See #158 , does the same as this one.

**Pull request closed without merging**
