### PR TITLE
Fix octave

### PR DESCRIPTION
**Pull request by andypfau**
Fixed verification of arguments in some Octave scripts

Fixed typos in several Octave scripts

### CODE REVIEW

**Comment by uandy741** [comment]
Added another fix: when openems.exe exits with non-zero, it propagates the error; before this, it just silently crashed, making it very hard to deiagnose crashes

**Comment by thliebig** [comment]
Looks all good so far. Two questions only: 
* Your username and mail address is a bit odd, do you want to amend those or keep it like this?
* openEMS.exe failing on Linux would not be a surprise to anyone ;) Maybe change to output to "openEMS binary exited with error-code..." ?

**Comment by andypfau** [comment]
Yeah, good point.... don't ask me why I was thinking Windows...

I don't know what's odd about my e-mail address, I guess you meant because it was not shown at all?

**Comment by thliebig** [comment]
With user and email being odd, I mean that the commits say this:
`Author: Andy <andy@desktop.fritz.box>`

**Comment by andypfau** [comment]
Ah that... yes I realized this, and fixed it, unfortunately too late. Only my last commit was done with the correct user config, the three older ones were with the global user config that git gratefully guessed for me.

I fail to find the location where those names are displayed. Help me please. If it is correct now, fine, otherwise I'd just commit the changes again with the correct user config.

**Comment by thliebig** [comment]
Well just do `git log` or gitk shows it too. I don't know which tool you use, but me on Linux its terminal only of course ;)

**Comment by thliebig** [comment]
And no the last commit is the same as the other three

**Comment by andypfau** [comment]
Nah I'm not religious about that... but as a matter of fact I use git from the shell, I just could not see it anywhere on GitHub.

But okay, I messed up my config, I start over, and ignore this pull request.

**Comment by andypfau** [comment]
See pull request #51

**Pull request closed without merging**
