### PR TITLE
tools/global.cpp: assign default verbose value.

### PR DESCRIPTION
**Pull request by biergaizi**
After commit 3c4e802638d4 ("Completely Rewrite Command-Line Argument Parsing"), the "verbose" option was assigned an implicit value (i.e. the value used for "-v" without an explicit number), but not a default value (i.e. the value used if no "-v" is given). This commit assigns a default value of 0 for logical consistency, and to allow the help message to show the default verbose value correctly.

### CODE REVIEW

**Comment by thliebig** [comment]
The patch looks good, but what does it solve? Running openEMS without -1 gives no verbosity and -v gives level 1 as expected?

**Comment by biergaizi** [comment]
Thanks for asking this question. Indeed, I found I've forgotten to apply the full bug fix... Please check the new commit messages.

## tools/global.cpp: assign default verbose value.
    
After commit 3c4e802638d4 ("Completely Rewrite Command-Line Argument Parsing"), the "verbose" option was assigned an implicit value (i.e. the value used for "-v" without an explicit number), but not a default value (i.e. the value used if no "-v" is given). Furthermore, if the default value "0" is given, no change to the runtime setting is made
    
This created two problems:
    
1. If openEMS is used as a shared library in Python, and the first simulation call is made with a non-default verbose value, but the second call is made with a default value, the second call has no effect - because the default value is only applied once on startup.
    
    This commit assigns a default value of 0 for "verbose" and applies this value on every invocation of the argument parser.
    
2. The (Boost-generated) help message doesn't show the default value "0", only the implicit value "1":
    
        -v [ --verbose ] [=arg(=1)]  Verbose level, select debug level 1 to 3, also
                                     accept -v, -vv, -vvv
    
    Furthermore, the help message now correct shows both the default and implicit value for "verbose":
    
        -v [ --verbose ] [=arg(=1)] (=0)  Verbose level, select debug level 1 to 3,
                                          also accept -v, -vv, -vvv

## tools/global.cpp: fix tab formatting.

Trivial space vs. tab fixes.

**Comment by thliebig** [comment]
Ok I understand. I assume you have tested this well? Because then I would only review it and not really test it much...

**Comment by biergaizi** [comment]
Yes, these changes have been tested.

During testing I've found another problem in the Python binding, also introduced in the new command-line argument parser, which I just fixed in an additional commit here.

## python: fix argument parsing logic.

The existing argument parsing logic has two problems. First, if an option is disabled by the boolean False, it's still treated as True. Next, people often use 0 for False, 1 for True, but it's ambiguous because boolean options accept no argument, but integer options accept a value.

Fix the second problem by converting 0/1 to False/True only for hardcoded non-integer options (currently we only have "verbose" and "numThreads"), and fix the first problem by ignoring False boolean options.

**Comment by thliebig** [comment]
@biergaizi Can you supply a very simple example that demonstrates the issue this PR is solving? Thanks.

**Comment by biergaizi** [comment]
Here is the minimal reproducible example.

```
import tempfile
from CSXCAD import ContinuousStructure
from openEMS import openEMS

mesh = {
    "x": range(-10, 10 + 1),
    "y": range(-10, 10 + 1),
    "z": range(-10, 30 + 1),
}

csx = ContinuousStructure()
csx.DefineGrid(mesh, unit=1)

exc = csx.AddExcitation('excitation', exc_type=0, exc_val=[0, 1, 0])
exc.AddBox([-10, -10, 0], [10, 10, 0])

fdtd = openEMS(NrTS=100, EndCriteria=0, OverSampling=50)
fdtd.SetCSX(csx)
fdtd.SetSinusExcite(10e6)
fdtd.SetBoundaryCond(('PMC', 'PMC', 'PEC', 'PEC', 'MUR', 'MUR'))

with tempfile.TemporaryDirectory() as tmpdir:
    fdtd.Run(tmpdir, verbose=3)
    fdtd.Run(tmpdir, verbose=False)
    fdtd.Run(tmpdir)
```


## Problem 1

If openEMS is used as a shared library in Python, and the first simulation call is made with a non-default verbose value, but a later call is made with a default value, the second call has no effect - because the default value is only applied once on startup.

If we run the example, we get verbose output for all FDTD simulations, even though only the last call has no `verbose` argument. This is because the verbose argument was only applied once in the first invocation, which is incorrect.

After applying this PR, the problem is fixed.

## Problem 2

If an option is disabled by the boolean `False`, it's still treated as `True`.

If we run the example, we get verbose output for

    fdtd.Run(tmpdir, verbose=False)

Because the `False` value is treated as if it's `True`.

After applying this PR, the problem is fixed.

**Pull request merged**
